<template>
  <section class="mx-auto max-w-7xl px-3 py-10 sm:px-6"><div class="flex flex-wrap items-end justify-between gap-5"><div><p class="text-xs uppercase tracking-[.3em] text-cyan-200">Communications</p><h1 class="mt-3 text-3xl font-black">Announcements</h1><p class="mt-3 text-slate-400">Draft, publish, archive, and remove event updates.</p></div><button class="primary" @click="openCreate">+ New announcement</button></div>
    <label class="field mt-8 block max-w-md"><span>Event</span><select v-model="eventId"><option v-for="event in events" :key="event.id" :value="event.id">{{ event.name }}</option></select></label><p v-if="feedback" class="mt-5 rounded-2xl border border-cyan-300/20 bg-cyan-300/10 p-4">{{ feedback }}</p>
    <div class="mt-6 overflow-x-auto rounded-[2rem] border border-white/10 bg-slate-950/45 data-table-shell"><table class="w-full min-w-[800px] text-left"><thead><tr><th>Title</th><th>Status</th><th>Published</th><th class="text-right">Actions</th></tr></thead><tbody><tr v-if="loading"><td colspan="4" class="py-12 text-center">Loading...</td></tr><tr v-else-if="!items.length"><td colspan="4" class="py-12 text-center">No announcements.</td></tr><tr v-for="item in items" v-else :key="item.id"><td data-label="Title"><strong>{{ item.title }}</strong><small>{{ item.body.slice(0,100) }}</small></td><td data-label="Status"><span class="pill">{{ item.status }}</span></td><td data-label="Published">{{ formatDate(item.published_at) }}</td><td data-label="Actions"><div class="flex justify-end gap-2"><button class="table-button" @click="openEdit(item)">Edit</button><button class="table-button text-red-200" @click="remove(item)">Delete</button></div></td></tr></tbody></table></div>
    <Teleport to="body"><div v-if="modalOpen" class="backdrop" @click.self="close"><form class="modal" @submit.prevent="save"><header><div><p class="text-xs uppercase tracking-[.25em] text-cyan-200">Announcement editor</p><h2>{{ editingId?'Update':'Create' }} announcement</h2></div><button type="button" @click="close">×</button></header><main><label class="field"><span>Title</span><input v-model.trim="form.title" required /></label><label class="field"><span>Message</span><textarea v-model.trim="form.body" rows="7" required /></label><div class="grid gap-4 sm:grid-cols-2"><label class="field"><span>Status</span><select v-model="form.status"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label class="field"><span>Published at</span><input v-model="form.published_at" type="datetime-local" /></label></div></main><footer><button type="button" class="secondary" @click="close">Cancel</button><button class="primary" :disabled="saving">{{saving?'Saving...':'Save'}}</button></footer></form></div></Teleport>
  </section>
</template>
<script setup lang="ts">
import {useAdminOperations,type AnnouncementPayload} from '~/composables/useAdminOperations';import {useEvent,type EventItem} from '~/composables/useEvent';import type{AnnouncementItem}from'~/composables/useEventUpdates';
definePageMeta({middleware:['auth','admin']});useSeoMeta({title:'Manage Announcements | IWBIF 2026'});const api=useAdminOperations(),{getEvents}=useEvent();const{data:eventResponse}=await useAsyncData('announcement-events',()=>getEvents(1,100));const events=computed<EventItem[]>(()=>eventResponse.value?.data||[]),eventId=ref(events.value[0]?.id||''),items=ref<AnnouncementItem[]>([]),loading=ref(false),saving=ref(false),modalOpen=ref(false),editingId=ref(''),feedback=ref('');type Form=Omit<AnnouncementPayload,'published_at'>&{published_at:string};const empty=():Form=>({title:'',body:'',status:'draft',published_at:''}),form=reactive(empty());const errorText=(e:unknown)=>(e as {data?:{message?:string}}).data?.message||(e instanceof Error?e.message:'Operation failed.');const local=(value?:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const load=async()=>{if(!eventId.value)return;loading.value=true;try{items.value=(await api.getAdminAnnouncements(eventId.value)).data||[];}catch(e){feedback.value=errorText(e);}finally{loading.value=false;}};const openCreate=()=>{editingId.value='';Object.assign(form,empty());modalOpen.value=true;};const openEdit=(item:AnnouncementItem)=>{editingId.value=item.id;Object.assign(form,{title:item.title,body:item.body,status:item.status||'draft',published_at:local(item.published_at)});modalOpen.value=true;};const close=()=>modalOpen.value=false;const save=async()=>{saving.value=true;const payload:AnnouncementPayload={...form,published_at:form.published_at?new Date(form.published_at).toISOString():null};try{if(editingId.value)await api.updateAnnouncement(editingId.value,payload);else await api.createAnnouncement(eventId.value,payload);feedback.value='Announcement saved.';close();await load();}catch(e){feedback.value=errorText(e);}finally{saving.value=false;}};const remove=async(item:AnnouncementItem)=>{if(!confirm(`Delete "${item.title}"?`))return;try{await api.deleteAnnouncement(item.id);await load();}catch(e){feedback.value=errorText(e);}};watch(eventId,load);if(eventId.value)await load();const formatDate=(v?:string|null)=>v?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
</script>
<style scoped>
section { font-family: 'Plus Jakarta Sans', 'Segoe UI', sans-serif; }
th{padding:1rem 1.25rem;background:#ffffff0a;font-size:.68rem;text-transform:uppercase;letter-spacing:.18em;color:#94a3b8}td{padding:1rem 1.25rem;border-top:1px solid #ffffff12;color:#cbd5e1}td strong,td small{display:block}td small{margin-top:.3rem;color:#64748b}.field span{display:block;margin-bottom:.5rem;font-size:.875rem;color:#cbd5e1}.field input,.field select,.field textarea{width:100%;border:1px solid #ffffff1a;border-radius:1rem;background:#020617d9;padding:.75rem 1rem;color:white}.primary,.secondary,.table-button{border-radius:999px;padding:.7rem 1.15rem;font-weight:800}.primary{background:#67e8f9;color:#083344}.secondary,.table-button{border:1px solid #ffffff26}.table-button{padding:.45rem .8rem;font-size:.75rem}.pill{border-radius:999px;background:#22d3ee1f;padding:.35rem .7rem;font-size:.65rem;text-transform:uppercase;color:#a5f3fc}.backdrop{position:fixed;inset:0;z-index:100;display:flex;align-items:center;justify-content:center;padding:1rem;background:#020617cc;backdrop-filter:blur(12px)}.modal{width:min(100%,44rem);overflow:hidden;border:1px solid #ffffff21;border-radius:2rem;background:linear-gradient(145deg,#071a36,#020d20)}.modal header,.modal footer{display:flex;align-items:center;justify-content:space-between;padding:1.25rem 1.75rem;border-bottom:1px solid #ffffff1a}.modal h2{margin-top:.5rem;font-size:1.5rem;font-weight:900}.modal header button{font-size:1.75rem}.modal main{display:grid;gap:1rem;padding:1.5rem 1.75rem}.modal footer{justify-content:flex-end;gap:.75rem;border-top:1px solid #ffffff1a;border-bottom:0}

@media (max-width: 767px) {
  section { padding-inline: 0.75rem; }
  .flex.flex-wrap.items-end.justify-between.gap-5 { flex-direction: column; align-items: stretch; }
  .primary { width: 100%; }
  .field input, .field select, .field textarea { width: 100%; }
  .data-table-shell { overflow: visible; }
  .data-table-shell table, .data-table-shell thead, .data-table-shell tbody, .data-table-shell tr, .data-table-shell th, .data-table-shell td { display: block; width: 100%; box-sizing: border-box; }
  .data-table-shell thead { display: none; }
  .data-table-shell tbody { display: grid; gap: 0.75rem; padding: 0.75rem; }
  .data-table-shell tr { border: 1px solid rgba(255,255,255,0.08); border-radius: 1.1rem; background: rgba(15,23,42,0.72); padding: 0.8rem; }
  .data-table-shell td { border: 0; padding: 0.35rem 0; display: flex; justify-content: space-between; gap: 0.75rem; font-size: 0.8rem; }
  .data-table-shell td::before { content: attr(data-label); color: #94a3b8; font-size: 0.64rem; letter-spacing: 0.14em; text-transform: uppercase; width: 36%; flex-shrink: 0; }
  .data-table-shell td > * { flex: 1; min-width: 0; }
  .modal { width: min(100%, 32rem); }
  .modal main, .modal header, .modal footer { padding-inline: 1rem; }
  .modal footer { flex-direction: column; }
  .modal footer button { width: 100%; }
}
</style>
