<template>
  <section class="mx-auto max-w-7xl px-3 py-10 sm:px-6 lg:px-8">
    <div class="flex flex-wrap items-end justify-between gap-5"><div><p class="text-sm uppercase tracking-[.3em] text-cyan-200">Event operations</p><h1 class="mt-3 text-3xl font-black sm:text-4xl">Program & agenda</h1><p class="mt-3 max-w-2xl text-sm leading-7 text-slate-300">Publish sessions and update their schedule, room, capacity, and visibility.</p></div><div class="flex flex-wrap gap-3"><NuxtLink to="/program" class="rounded-full border border-cyan-300/30 px-5 py-3 text-sm font-semibold text-cyan-100">View public program</NuxtLink><NuxtLink to="/dashboard" class="rounded-full border border-white/20 px-5 py-3 text-sm font-semibold">Dashboard</NuxtLink></div></div>
    <label class="mt-8 block max-w-md text-sm text-slate-300"><span class="mb-2 block">Event</span><select v-model="selectedEventId" class="w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300/50"><option v-for="event in events" :key="event.id" :value="event.id">{{ event.name }}</option></select></label>
    <div v-if="feedback" class="mt-5 rounded-2xl border p-4 text-sm" :class="feedbackTone === 'error' ? 'border-red-400/30 bg-red-950/30 text-red-100' : 'border-emerald-300/30 bg-emerald-950/30 text-emerald-100'">{{ feedback }}</div>

    <div class="mt-8 grid gap-6 lg:grid-cols-[1fr_25rem]">
      <div class="space-y-4">
        <p v-if="loading" class="glass-card rounded-3xl p-6 text-slate-300">Loading agenda...</p><p v-else-if="!sessions.length" class="glass-card rounded-3xl p-6 text-slate-300">No sessions are available for this event.</p>
        <article v-for="session in sessions" v-else :key="session.id" class="glass-card rounded-3xl p-5 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-cyan-300/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[.18em] text-cyan-200">{{ session.session_type || 'Session' }}</span><span class="rounded-full bg-white/10 px-3 py-1 text-[10px] uppercase tracking-[.16em] text-slate-300">{{ session.status || 'published' }}</span></div><h2 class="mt-3 text-xl font-bold">{{ session.title }}</h2><p class="mt-2 text-sm text-slate-400">{{ formatDate(session.start_at) }} · {{ session.room_name || 'Room TBA' }}</p></div><button class="rounded-full border border-cyan-300/30 px-5 py-2 text-sm font-semibold text-cyan-100" @click="editSession(session)">Edit session</button></div></article>
      </div>

      <form class="glass-card h-fit rounded-[2rem] p-5 sm:p-6" @submit.prevent="saveSession"><div class="flex items-center justify-between gap-3"><h2 class="text-xl font-bold">{{ editingId ? 'Update session' : 'New session' }}</h2><button v-if="editingId" type="button" class="text-sm text-slate-400" @click="resetForm">Cancel</button></div><div class="mt-5 space-y-4">
        <label class="field"><span>Session title</span><input v-model.trim="form.title" required /></label><label class="field"><span>Slug</span><input v-model.trim="form.slug" placeholder="business-forum-opening" /></label><label class="field"><span>Description</span><textarea v-model.trim="form.description" rows="3" /></label>
        <div class="grid grid-cols-2 gap-3"><label class="field"><span>Session type</span><input v-model.trim="form.session_type" placeholder="panel" /></label><label class="field"><span>Room</span><input v-model.trim="form.room_name" placeholder="Grand Ballroom" /></label></div>
        <label class="field"><span>Starts at</span><input v-model="form.start_at" type="datetime-local" required /></label><label class="field"><span>Ends at</span><input v-model="form.end_at" type="datetime-local" required /></label>
        <div class="grid grid-cols-2 gap-3"><label class="field"><span>Capacity</span><input v-model.number="form.capacity" type="number" min="1" /></label><label class="field"><span>Status</span><select v-model="form.status"><option value="draft">Draft</option><option value="published">Published</option><option value="canceled">Canceled</option></select></label></div>
        <button class="w-full rounded-full bg-cyan-300 px-5 py-3 font-bold text-slate-950 disabled:opacity-50" :disabled="saving || !selectedEventId">{{ saving ? 'Saving...' : editingId ? 'Update session' : 'Create session' }}</button>
      </div></form>
    </div>
  </section>
</template>

<script setup lang="ts">
import {useEvent,type EventItem,type SessionItem} from '~/composables/useEvent';import {useAdminContent,type SessionMutationPayload} from '~/composables/useAdminContent';
definePageMeta({middleware:['auth','admin']});useSeoMeta({title:'Manage Program | IWBIF 2026'});const {getEvents}=useEvent();const adminApi=useAdminContent();const {data:eventResponse}=await useAsyncData('admin-program-events',()=>getEvents(1,100));const events=computed<EventItem[]>(()=>eventResponse.value?.data||[]);const selectedEventId=ref(events.value[0]?.id||'');const selectedEvent=computed(()=>events.value.find(event=>event.id===selectedEventId.value));
const sessions=ref<SessionItem[]>([]);const loading=ref(false),saving=ref(false),editingId=ref(''),feedback=ref('');const feedbackTone=ref<'success'|'error'>('success');type SessionForm=Omit<SessionMutationPayload,'start_at'|'end_at'>&{start_at:string;end_at:string};const emptyForm=():SessionForm=>({title:'',slug:'',description:'',session_type:'session',room_name:'',start_at:'',end_at:'',capacity:null,status:'published'});const form=reactive<SessionForm>(emptyForm());
const apiError=(error:unknown)=>{const value=error as {data?:{message?:string;errors?:Array<{message:string}>}};return value.data?.errors?.[0]?.message||value.data?.message||(error instanceof Error?error.message:'The session could not be saved.');};const localDate=(value:string)=>{const date=new Date(value);const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);};
const loadSessions=async()=>{if(!selectedEvent.value?.slug){sessions.value=[];return;}loading.value=true;feedback.value='';try{sessions.value=(await adminApi.getSessions(selectedEvent.value.slug)).data||[];}catch(error){feedbackTone.value='error';feedback.value=apiError(error);}finally{loading.value=false;}};const resetForm=()=>{editingId.value='';Object.assign(form,emptyForm());};
const editSession=(session:SessionItem)=>{editingId.value=session.id;Object.assign(form,{title:session.title,slug:session.slug||'',description:session.description||'',session_type:session.session_type||'session',room_name:session.room_name||'',start_at:localDate(session.start_at),end_at:localDate(session.end_at),capacity:session.capacity??null,status:session.status||'published'});};
const saveSession=async()=>{if(!selectedEventId.value||saving.value)return;if(new Date(form.end_at)<=new Date(form.start_at)){feedbackTone.value='error';feedback.value='End time must be after start time.';return;}saving.value=true;feedback.value='';const payload={...form,slug:form.slug||null,description:form.description||null,room_name:form.room_name||null,capacity:form.capacity||null,start_at:new Date(form.start_at).toISOString(),end_at:new Date(form.end_at).toISOString()};try{if(editingId.value)await adminApi.updateSession(editingId.value,payload);else await adminApi.createSession({...payload,event_id:selectedEventId.value});feedbackTone.value='success';feedback.value=editingId.value?'Session updated.':'Session created.';resetForm();await loadSessions();}catch(error){feedbackTone.value='error';feedback.value=apiError(error);}finally{saving.value=false;}};
watch(selectedEventId,async()=>{resetForm();await loadSessions();});if(selectedEventId.value)await loadSessions();const formatDate=(value:string)=>new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(value));
</script>

<style scoped>.field { display:block; font-size:.875rem; color:#cbd5e1; }.field span { display:block; margin-bottom:.5rem; }.field input,.field select,.field textarea { width:100%; border:1px solid rgba(255,255,255,.1); border-radius:1rem; background:rgba(2,6,23,.78); padding:.75rem 1rem; color:white; outline:none; }.field input:focus,.field select:focus,.field textarea:focus { border-color:rgba(103,232,249,.5); }</style>
