<template>
  <section class="mx-auto max-w-4xl px-3 py-10 sm:px-6"><div class="glass-card rounded-[2rem] p-4 sm:p-7">
    <p class="text-sm uppercase tracking-[.3em] text-amber-200">Secure payment</p><h1 class="mt-3 text-3xl font-black sm:text-4xl">Choose payment method</h1>
    <p class="mt-3 text-sm text-slate-300">The backend determines the final amount from your delegate package.</p>
    <p v-if="loading" class="mt-8 text-slate-300">Checking registration and active payment channels…</p>
    <div v-else-if="paid" class="mt-8 rounded-2xl border border-emerald-300/20 bg-emerald-300/5 p-5"><p class="text-lg font-semibold text-emerald-300">Payment received</p><p class="mt-2 text-sm text-slate-300">Organizer confirmation is handled separately.</p><NuxtLink :to="`/dashboard/invoice?registration_id=${registrationId}`" class="mt-5 inline-flex rounded-full bg-amber-300 px-5 py-3 font-semibold text-slate-950">View invoice</NuxtLink></div>
    <div v-else-if="!registrationId" class="notice">No registration eligible for payment was found.</div>
    <div v-else-if="!methods.length" class="notice">Payment methods are not available yet. Please try again later.</div>
    <template v-else><div class="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
      <button v-for="method in methods" :key="method.id" type="button" class="flex min-h-24 items-center gap-4 rounded-2xl border p-4 text-left transition disabled:cursor-not-allowed disabled:opacity-50" :class="selected?.id === method.id ? 'border-amber-300 bg-amber-300/10' : 'border-white/10 bg-white/5 hover:border-white/30'" :disabled="!isSupported(method)" @click="selected = method">
        <img v-if="method.logo_url && !brokenLogos.has(method.id)" :src="method.logo_url" :alt="method.display_name" class="h-10 w-14 rounded bg-white object-contain p-1" @error="brokenLogos.add(method.id)"><span v-else class="flex h-10 w-14 items-center justify-center rounded bg-white/10 text-xs font-bold">{{ method.code }}</span>
        <span><strong class="block">{{ method.display_name }}</strong><small class="mt-1 block text-slate-400">{{ categoryLabel(method.category) }}<template v-if="!isSupported(method)"> · Coming soon</template></small></span>
      </button>
    </div>
    <div v-if="selected?.category === 'direct_debit'" class="mt-6 max-w-md space-y-3"><label class="block text-sm text-slate-300">Mobile number registered with the bank<input v-model.trim="phoneNo" inputmode="tel" autocomplete="tel" placeholder="628123456789" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950/50 px-4 py-3 text-white"></label><label class="block text-sm text-slate-300">Device ID <span class="text-slate-500">(optional)</span><input v-model.trim="deviceId" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950/50 px-4 py-3 text-white"></label></div>
    <button class="mt-6 w-full rounded-full bg-amber-300 px-6 py-3 font-semibold text-slate-950 disabled:opacity-50 sm:w-auto" :disabled="!selected || submitting || (selected.category === 'direct_debit' && !phoneNo)" @click="startPayment">{{ submitting ? 'Preparing payment…' : 'Continue' }}</button></template>
    <div v-if="va" class="mt-8 rounded-2xl border border-amber-300/20 bg-white/5 p-5"><p class="text-sm text-slate-400">{{ va.bank_code }} Virtual Account</p><p class="mt-2 break-all text-2xl font-black text-amber-200">{{ va.virtual_account_no }}</p><p class="mt-3">{{ money(va.amount, va.currency) }}<span v-if="va.expires_at" class="text-slate-400"> · Expires {{ formatDate(va.expires_at) }}</span></p><div class="mt-4 flex flex-wrap gap-3"><button class="rounded-full bg-amber-300 px-5 py-2 font-semibold text-slate-950" @click="copyVa">{{ copied ? 'Copied' : 'Copy VA number' }}</button><a v-if="va.instructions_url" :href="va.instructions_url" target="_blank" rel="noopener noreferrer" class="rounded-full border border-white/20 px-5 py-2">Payment instructions</a></div></div>
    <div v-if="qris" class="mt-8 rounded-2xl border border-amber-300/20 bg-white/5 p-5 text-center"><p class="font-semibold">Scan this QRIS code</p><img v-if="qrImage" :src="qrImage" alt="QRIS payment code" class="mx-auto mt-4 w-64 rounded-xl bg-white p-3"><p class="mt-3">{{ money(qris.amount, qris.currency) }}</p><p v-if="qris.expires_at" class="mt-1 text-sm text-slate-400">Expires {{ formatDate(qris.expires_at) }}</p></div>
    <div v-if="selected?.category === 'direct_debit' && bindingId && !activePaymentId" class="mt-8 rounded-2xl border border-amber-300/20 bg-white/5 p-5"><p class="font-semibold">Bank account authorization</p><p class="mt-2 text-sm text-slate-300">Complete the bank authorization, then continue to create the payment.</p><button class="mt-4 rounded-full bg-amber-300 px-5 py-2 font-semibold text-slate-950 disabled:opacity-50" :disabled="submitting" @click="continueDirectDebit">Continue payment</button></div>
    <div v-if="needsOtp" class="mt-8 max-w-md rounded-2xl border border-amber-300/20 bg-white/5 p-5"><label class="block text-sm text-slate-300">Bank OTP<input v-model.trim="otp" inputmode="numeric" autocomplete="one-time-code" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-950/50 px-4 py-3 text-white"></label><button class="mt-4 rounded-full bg-amber-300 px-5 py-2 font-semibold text-slate-950 disabled:opacity-50" :disabled="submitting || !otp" @click="submitOtp">Submit OTP</button></div>
    <NuxtLink v-if="activePaymentId" :to="`/dashboard/payment-status?payment_id=${activePaymentId}&registration_id=${registrationId}`" class="mt-5 inline-flex rounded-full border border-white/20 px-5 py-3">Check payment status</NuxtLink>
    <div v-if="errorMessage" class="mt-5 rounded-2xl border border-red-400/30 bg-red-950/30 p-4 text-sm text-red-100"><p>{{ errorMessage }}</p><p v-if="requestId" class="mt-2 text-xs opacity-70">Reference: {{ requestId }}</p></div>
  </div></section>
</template>

<script setup lang="ts">
import QRCode from 'qrcode';
import { normalizeInvoices, usePayment, type DirectQrisData, type DirectVaData, type PaymentMethod } from '~/composables/usePayment';
import { useRegistration } from '~/composables/useRegistration';
definePageMeta({ middleware: 'auth' }); useSeoMeta({ title: 'Payment | IWBIF 2026' });
const paymentApi = usePayment(); const { getMyRegistrations } = useRegistration();
const loading = ref(true), submitting = ref(false), paid = ref(false), copied = ref(false), needsOtp = ref(false); const registrationId = ref(''), activePaymentId = ref(''), errorMessage = ref(''), requestId = ref(''), qrImage = ref(''), phoneNo = ref(''), deviceId = ref(''), bindingId = ref(''), otp = ref('');
const methods = ref<PaymentMethod[]>([]), selected = ref<PaymentMethod | null>(null), va = ref<DirectVaData | null>(null), qris = ref<DirectQrisData | null>(null); const brokenLogos = reactive(new Set<string>()); const direct = ref({ virtual_accounts: [] as string[], qris: false });
const apiError = (error: unknown) => { const value = error as { data?: { message?: string; request_id?: string; errors?: Array<{ message: string }> } }; requestId.value = value.data?.request_id || ''; return value.data?.errors?.[0]?.message || value.data?.message || (error instanceof Error ? error.message : 'Payment could not be prepared.'); };
const isSupported = (method: PaymentMethod) => method.category === 'virtual_account' ? direct.value.virtual_accounts.map(code => code.toUpperCase()).includes(method.code.toUpperCase()) : method.category === 'qris' ? direct.value.qris : method.category === 'direct_debit';
const rememberPayment = () => { sessionStorage.setItem('iwbif-doku-registration-id', registrationId.value); if (bindingId.value) sessionStorage.setItem('iwbif-doku-binding-id', bindingId.value); if (selected.value?.category === 'direct_debit') sessionStorage.setItem('iwbif-doku-binding-channel', selected.value.code); if (activePaymentId.value) sessionStorage.setItem('iwbif-doku-payment-id', activePaymentId.value); };
const continueDirectDebit = async () => { if (!bindingId.value || submitting.value) return; submitting.value = true; errorMessage.value = ''; try { const result = (await paymentApi.createDirectDebitPayment(registrationId.value, bindingId.value)).data; activePaymentId.value = result.payment_id; needsOtp.value = result.requires_otp === true || result.status?.toLowerCase().includes('otp'); rememberPayment(); if (result.redirect_url) window.location.assign(result.redirect_url); } catch (error) { errorMessage.value = apiError(error); } finally { submitting.value = false; } };
const startPayment = async () => { if (!selected.value || submitting.value) return; submitting.value = true; errorMessage.value = ''; va.value = null; qris.value = null; try { if (selected.value.category === 'virtual_account') { bindingId.value = ''; va.value = (await paymentApi.createDirectVa(registrationId.value, selected.value.code)).data; activePaymentId.value = va.value.payment_id; } else if (selected.value.category === 'qris') { bindingId.value = ''; qris.value = (await paymentApi.createDirectQris(registrationId.value)).data; activePaymentId.value = qris.value.payment_id; qrImage.value = await QRCode.toDataURL(qris.value.qr_content, { width: 320, margin: 1 }); } else if (selected.value.category === 'direct_debit') { const result = (await paymentApi.createDirectDebitBinding(registrationId.value, selected.value.code, phoneNo.value, deviceId.value)).data; bindingId.value = result.binding_id; rememberPayment(); if (result.redirect_url) { window.location.assign(result.redirect_url); return; } } rememberPayment(); } catch (error) { errorMessage.value = apiError(error); } finally { submitting.value = false; } if (selected.value.category === 'direct_debit' && bindingId.value) await continueDirectDebit(); };
const submitOtp = async () => { if (!activePaymentId.value || !bindingId.value || !otp.value || submitting.value) return; submitting.value = true; errorMessage.value = ''; try { const result = (await paymentApi.submitDirectDebitOtp(activePaymentId.value, bindingId.value, otp.value)).data; needsOtp.value = result.requires_otp === true || result.status?.toLowerCase().includes('otp'); if (result.redirect_url) window.location.assign(result.redirect_url); } catch (error) { errorMessage.value = apiError(error); } finally { submitting.value = false; } };
onMounted(async () => { try { bindingId.value = sessionStorage.getItem('iwbif-doku-binding-id') || ''; const bindingChannel = sessionStorage.getItem('iwbif-doku-binding-channel') || ''; const response = await getMyRegistrations(); const items = Array.isArray(response.data) ? response.data : []; const chosen = items.find(item => ['draft', 'awaiting_payment', 'payment_pending', 'verified'].includes(item.status)) || items[0]; if (chosen) registrationId.value = chosen.id; try { const invoice = normalizeInvoices((await paymentApi.getMyInvoices()).data).find(item => item.registration.id === registrationId.value); paid.value = invoice?.order.status?.toLowerCase() === 'paid' || invoice?.payment.transaction_status?.toLowerCase() === 'success'; } catch {} if (!paid.value && registrationId.value) { const [catalog, availability] = await Promise.all([paymentApi.getPaymentMethods(), paymentApi.getDirectPaymentMethods()]); methods.value = [...catalog.data].filter(method => method.category !== 'e_wallet').sort((a, b) => a.sort_order - b.sort_order); direct.value = availability.data; if (bindingId.value && bindingChannel) selected.value = methods.value.find(method => method.category === 'direct_debit' && method.code === bindingChannel) || null; } } catch (error) { errorMessage.value = apiError(error); } finally { loading.value = false; } });
const copyVa = async () => { if (!va.value) return; await navigator.clipboard.writeText(va.value.virtual_account_no); copied.value = true; setTimeout(() => { copied.value = false; }, 2000); };
const categoryLabel = (value: string) => ({ virtual_account: 'Virtual Account', qris: 'QRIS', e_wallet: 'e-Wallet', direct_debit: 'Direct Debit' }[value] || value); const money = (amount: number, code: string) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: code || 'IDR', maximumFractionDigits: 0 }).format(amount); const formatDate = (value: string) => new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
</script>

<style scoped>.notice { @apply mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5 text-amber-100; }</style>
