<template>
  <section class="mx-auto max-w-4xl px-3 py-10 sm:px-6">
    <div class="glass-card rounded-[2rem] p-4 sm:p-7">
      <p class="text-sm uppercase tracking-[.3em] text-amber-200">Secure payment</p><h1 class="mt-3 text-3xl font-black sm:text-4xl">Complete your package order</h1><p class="mt-3 text-sm text-slate-300">The final amount comes directly from your backend order. You will continue to DOKU to pay securely.</p>
      <p v-if="loading" class="mt-8 text-slate-300">Loading your order...</p>
      <div v-else-if="!orderId" class="notice"><p>No active order was found. Review your cart and create an order first.</p><NuxtLink to="/dashboard/cart" class="mt-5 inline-flex rounded-full bg-amber-300 px-5 py-3 font-semibold text-slate-950">Open cart</NuxtLink></div>
      <template v-else>
        <div class="mt-8 rounded-2xl border border-white/10 bg-white/5 p-5"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs uppercase tracking-[.2em] text-slate-400">Order</p><p class="mt-2 text-xl font-bold">{{ order?.order_number || orderId }}</p></div><span class="rounded-full border border-amber-300/20 bg-amber-300/10 px-3 py-1 text-xs uppercase tracking-[.18em] text-amber-100">{{ order?.status || 'pending' }}</span></div><div v-if="order" class="mt-5 flex items-end justify-between border-t border-white/10 pt-5"><span class="text-slate-400">Total</span><strong class="text-2xl text-amber-200">{{ money(order.total_amount,order.currency) }}</strong></div></div>
        <div class="mt-6 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><NuxtLink v-if="isPaid" :to="`/dashboard/invoice?order_id=${orderId}`" class="rounded-full bg-emerald-300 px-6 py-3 text-center font-bold text-slate-950">View invoice</NuxtLink><button v-else class="rounded-full bg-amber-300 px-6 py-3 font-bold text-slate-950 disabled:cursor-not-allowed disabled:opacity-60" :disabled="submitting" @click="startPayment">{{ submitting ? 'Preparing DOKU checkout...' : 'Pay with DOKU' }}</button><NuxtLink to="/dashboard/cart" class="rounded-full border border-white/20 px-6 py-3 text-center">Back to cart</NuxtLink></div>
      </template>
      <div v-if="errorMessage" class="mt-5 rounded-2xl border border-red-400/30 bg-red-950/30 p-4 text-sm text-red-100"><p>{{ errorMessage }}</p><p v-if="requestId" class="mt-2 text-xs opacity-70">Reference: {{ requestId }}</p></div>
    </div>
  </section>
</template>
<script setup lang="ts">
import {usePayment,type OrderItem} from '~/composables/usePayment';
definePageMeta({middleware:'auth'});useSeoMeta({title:'Payment | IWBIF 2026'});const route=useRoute();const paymentApi=usePayment();const orderId=ref(''),paymentId=ref(''),errorMessage=ref(''),requestId=ref('');const order=ref<OrderItem|null>(null);const loading=ref(true),submitting=ref(false);const isPaid=computed(()=>order.value?.status?.toLowerCase()==='paid');const queryValue=(value:unknown)=>Array.isArray(value)?String(value[0]||''):typeof value==='string'?value:'';
const apiError=(error:unknown)=>{const value=error as {data?:{message?:string;request_id?:string;errors?:Array<{message:string}>}};requestId.value=value.data?.request_id||'';return value.data?.errors?.[0]?.message||value.data?.message||(error instanceof Error?error.message:'Payment could not be prepared.');};
const startPayment=async()=>{if(!orderId.value||submitting.value)return;submitting.value=true;errorMessage.value='';try{const checkout=(await paymentApi.createDokuCheckout(orderId.value)).data;paymentId.value=checkout.payment_id||'';sessionStorage.setItem('iwbif-store-order-id',orderId.value);if(paymentId.value)sessionStorage.setItem('iwbif-doku-payment-id',paymentId.value);if(!checkout.requires_payment||checkout.already_paid){await navigateTo(`/dashboard/invoice?order_id=${encodeURIComponent(orderId.value)}`);return;}if(checkout.payment_url){window.location.assign(checkout.payment_url);return;}await navigateTo(`/dashboard/payment-status?order_id=${encodeURIComponent(orderId.value)}&payment_id=${encodeURIComponent(paymentId.value)}`);}catch(error){errorMessage.value=apiError(error);}finally{submitting.value=false;}};
onMounted(async()=>{orderId.value=queryValue(route.query.order_id)||sessionStorage.getItem('iwbif-store-order-id')||'';if(orderId.value){try{order.value=(await paymentApi.getOrder(orderId.value)).data;}catch(error){errorMessage.value=apiError(error);}}loading.value=false;});const money=(amount:number,currency:string)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:currency||'IDR',maximumFractionDigits:0}).format(amount||0);
</script>
<style scoped>.notice { @apply mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5 text-amber-100; }</style>
