// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 23/08/2026, 10.58.46
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/projek/nuxt-event/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/projek/nuxt-event/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/projek/nuxt-event/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/projek/nuxt-event/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/projek/nuxt-event/app/plugins/**/*.{js,ts,mjs}","C:/projek/nuxt-event/app/composables/**/*.{js,ts,mjs}","C:/projek/nuxt-event/app/utils/**/*.{js,ts,mjs}","C:/projek/nuxt-event/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/projek/nuxt-event/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/projek/nuxt-event/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/projek/nuxt-event/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;