<template>
  <div>
    <section class="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-24">
      <div class="self-center"><p class="text-sm font-semibold uppercase tracking-[.3em] text-amber-200">14–17 October 2026 · Jakarta, Indonesia</p><h1 class="mt-6 text-5xl font-black leading-[.96] sm:text-6xl lg:text-7xl">International Women Business &amp; Investment Forum 2026</h1><p class="mt-6 max-w-2xl text-xl italic leading-8 text-slate-200">Empowering Women Entrepreneurs Through Finance, Global Collaboration, and Digital Transformation.</p><p class="mt-5 max-w-2xl leading-8 text-slate-400">Join women entrepreneurs, investors, business leaders, government representatives, financial institutions, and global partners in a trusted ecosystem for cross-border growth.</p><div class="mt-8 flex flex-wrap gap-3"><NuxtLink to="/register" class="rounded-full bg-amber-300 px-6 py-3 font-semibold text-slate-950">Register Now</NuxtLink><NuxtLink to="/program" class="rounded-full border border-white/20 px-6 py-3 font-semibold">Explore the Program</NuxtLink><NuxtLink to="/partners" class="rounded-full border border-amber-300/30 px-6 py-3 font-semibold text-amber-100">Become a Partner</NuxtLink></div><div class="mt-9 grid gap-3 sm:grid-cols-2"><p class="glass-card rounded-2xl p-4 text-sm text-slate-300"><strong class="block text-white">Hotel Kempinski Indonesia</strong>Jakarta, Indonesia</p><p class="glass-card rounded-2xl p-4 text-sm text-slate-300"><strong class="block text-white">International Forum</strong>English, Indonesian, and Chinese</p></div></div>
      <div class="glass-card flex min-h-[480px] items-end rounded-[2.5rem] p-7"><div><p class="text-sm uppercase tracking-[.3em] text-amber-200">Connect · Collaborate · Create</p><p class="mt-3 text-3xl font-bold">Turn trusted connections into global business opportunities.</p><p class="mt-4 leading-7 text-slate-300">Forum discussions, curated business matching, partner exhibition, and an industrial visit in one delegate journey.</p></div></div>
    </section>
    <section class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><article v-for="stat in stats" :key="stat.value" class="glass-card rounded-3xl p-5"><strong class="text-3xl text-white">{{ stat.value }}</strong><p class="mt-2 text-sm leading-6 text-slate-400">{{ stat.label }}</p></article></div></section>
    <section class="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p class="text-sm uppercase tracking-[.35em] text-amber-200">A trusted global ecosystem</p><h2 class="mt-4 text-4xl font-black">Build bridges. Unlock investment. Accelerate partnerships.</h2><p class="mt-5 text-lg leading-8 text-slate-300">IWBIF brings women entrepreneurs together with buyers, investors, embassies, business networks, and ecosystem leaders. The forum supports transparent, inclusive, and sustainable women-led business collaboration.</p><NuxtLink to="/about" class="mt-7 inline-flex text-sm font-semibold text-amber-200">Discover why Indonesia →</NuxtLink></div><div class="grid gap-4 sm:grid-cols-2"><article v-for="item in experiences" :key="item.title" class="glass-card rounded-3xl p-6"><h3 class="text-xl font-bold">{{ item.title }}</h3><p class="mt-3 text-sm leading-7 text-slate-300">{{ item.text }}</p></article></div></section>
    <section class="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div class="rounded-[2.5rem] border border-amber-300/20 bg-amber-300/10 p-8 text-center sm:p-12"><p class="text-sm uppercase tracking-[.35em] text-amber-100">IWBIF 2026</p><h2 class="mt-4 text-4xl font-black">Connect. Match. Make Deals.</h2><p class="mx-auto mt-4 max-w-2xl text-slate-300">Explore new markets, investment opportunities, strategic partnerships, and cross-border business connections.</p><div class="mt-7 flex flex-wrap justify-center gap-3"><NuxtLink to="/register" class="rounded-full bg-amber-300 px-6 py-3 font-semibold text-slate-950">Register Now</NuxtLink><NuxtLink to="/business-matching" class="rounded-full border border-white/20 px-6 py-3 font-semibold">Business Matching</NuxtLink></div></div></section>
  </div>
</template>
<script setup lang="ts">useSeoMeta({title:'IWBIF 2026 | International Women Business & Investment Forum',description:'Join IWBIF 2026 in Jakarta, 14–17 October, for global collaboration, investment, and women-led business growth.',ogTitle:'International Women Business & Investment Forum 2026',ogDescription:'Connect. Collaborate. Create.'}); const stats=[{value:'500+',label:'International delegates'},{value:'2 Days',label:'Core business forum program'},{value:'6',label:'Business matching sectors'},{value:'3',label:'International business networks'},{value:'1',label:'Industrial visit'},{value:'9+',label:'Global speakers'}]; const experiences=[{title:'Keynote Sessions',text:'Strategic perspectives from government and global business leaders.'},{title:'Expert Panels',text:'Finance, digital transformation, markets, and cross-border collaboration.'},{title:'Business Matching',text:'Curated meetings with buyers, investors, distributors, and partners.'},{title:'Partner Exhibition',text:'A premium showcase for women-led products, services, and opportunities.'}];</script>
