<template>
  <div>
    <section class="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-20">
      <div class="self-center">
        <p class="text-sm font-semibold uppercase tracking-[0.35em] text-cyan-200">18–19 November 2026 · Jakarta</p>
        <h1 class="mt-6 text-5xl font-black leading-[.96] sm:text-6xl lg:text-7xl">Building AI for the Future of ASEAN Education</h1>
        <p class="mt-6 max-w-2xl text-lg leading-8 text-slate-300">A two-day international summit and developer workshop connecting technology professionals, educators, researchers, and institutions to create practical AI solutions for students and schools across Southeast Asia.</p>
        <div class="mt-8 flex flex-wrap gap-3"><NuxtLink to="/register" class="rounded-full bg-cyan-400 px-6 py-3 font-semibold text-slate-950">Register Now</NuxtLink><NuxtLink to="/program" class="rounded-full border border-white/20 px-6 py-3 font-semibold">Explore the Program</NuxtLink><NuxtLink to="/partners" class="rounded-full border border-orange-300/30 px-6 py-3 font-semibold text-orange-100">Become a Partner</NuxtLink></div>
        <div class="mt-9 grid gap-3 sm:grid-cols-2"><p class="glass-card rounded-2xl p-4 text-sm text-slate-300"><strong class="block text-white">Jakarta Convention Center</strong>Jakarta, Indonesia</p><p class="glass-card rounded-2xl p-4 text-sm text-slate-300"><strong class="block text-white">International Summit</strong>Technical conference and hands-on workshop</p></div>
      </div>
      <div class="relative"><img src="/foto/masa_depan.png" alt="The bright future of artificial intelligence" class="h-full min-h-[480px] w-full rounded-[2.5rem] object-cover" /><div class="absolute bottom-5 left-5 right-5 rounded-3xl border border-white/15 bg-slate-950/80 p-5 backdrop-blur"><p class="text-sm uppercase tracking-[0.3em] text-orange-200">Main tagline</p><p class="mt-2 text-2xl font-bold">Build AI. Transform Education. Connect ASEAN.</p></div></div>
    </section>

    <section class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><article v-for="stat in stats" :key="stat.value" class="glass-card rounded-3xl p-5"><strong class="text-3xl text-white">{{ stat.value }}</strong><p class="mt-2 text-sm leading-6 text-slate-400">{{ stat.label }}</p></article></div></section>

    <section class="mx-auto grid max-w-7xl gap-7 px-4 py-14 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p class="text-sm uppercase tracking-[0.35em] text-cyan-200">A Regional Movement</p><h2 class="mt-4 text-4xl font-black">From conversation to practical solutions.</h2><p class="mt-5 text-lg leading-8 text-slate-300">Artificial intelligence is transforming how people learn, teach, collaborate, and access information. This summit creates a regional platform where developers, educators, researchers, startups, universities, governments, and technology companies build responsibly together.</p><NuxtLink to="/about" class="mt-7 inline-flex text-sm font-semibold text-cyan-200">Discover why this event matters →</NuxtLink></div><img src="/foto/ai_summit2.png" alt="ASEAN technology professionals collaborating" class="h-80 w-full rounded-[2rem] object-cover" /></section>

    <section class="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><p class="text-sm uppercase tracking-[0.35em] text-orange-200">Event Experience</p><h2 class="mt-4 text-4xl font-black">Two intensive days of learning and building.</h2><div class="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><article v-for="item in experiences" :key="item.title" class="glass-card rounded-3xl p-6"><h3 class="text-xl font-bold">{{ item.title }}</h3><p class="mt-3 text-sm leading-7 text-slate-300">{{ item.text }}</p></article></div></section>

    <section class="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div class="overflow-hidden rounded-[2.5rem] border border-cyan-300/20 bg-cyan-300/10 p-8 text-center sm:p-12"><p class="text-sm uppercase tracking-[.35em] text-cyan-100">ASEAN's AI Community</p><h2 class="mx-auto mt-4 max-w-4xl text-4xl font-black">Build the Future of Education With Us</h2><p class="mx-auto mt-4 max-w-2xl text-slate-300">Two days of learning. Two days of building. A long-term ASEAN network.</p><div class="mt-7 flex flex-wrap justify-center gap-3"><NuxtLink to="/register" class="rounded-full bg-cyan-400 px-6 py-3 font-semibold text-slate-950">Register Now</NuxtLink><NuxtLink to="/tickets" class="rounded-full border border-white/20 px-6 py-3 font-semibold">View Ticket Options</NuxtLink></div></div></section>
  </div>
</template>
<script setup lang="ts">
useSeoMeta({title:'ASEAN AI for Education Summit 2026',description:'A two-day international AI summit and developer workshop in Jakarta, 18–19 November 2026.',ogTitle:'Build AI. Transform Education. Connect ASEAN.',ogDescription:'Join developers, educators, and institutions building practical AI solutions for education.',ogImage:'/foto/masa_depan.png'});
const stats=[{value:'10',label:'ASEAN Countries'},{value:'300+',label:'Participants'},{value:'20+',label:'Speakers and Mentors'},{value:'12',label:'Technical Sessions'},{value:'5',label:'Workshop Tracks'}];
const experiences=[{title:'Keynote Sessions',text:'Hear regional and international leaders discuss AI, education, workforce development, and collaboration.'},{title:'Technical Workshops',text:'Build with AI architecture, prompt engineering, RAG, machine learning, analytics, and deployment.'},{title:'Collaborative Development',text:'Join multidisciplinary teams, solve real educational challenges, and demonstrate a prototype.'},{title:'ASEAN Networking',text:'Meet developers, researchers, educators, founders, institutions, and technology partners.'}];
</script>
