const interopDefault = r => r.default || r || [];
const styles = {
  "../node_modules/nuxt/dist/app/entry.js": () => import('../build/entry-styles.2ecgrAw2.mjs').then(interopDefault),
  "app.vue": () => import('../build/entry-styles.2ecgrAw2.mjs').then(interopDefault),
  "pages/auth/login.vue": () => import('../build/login-styles.NSwfjpz-.mjs').then(interopDefault),
  "pages/auth/register.vue": () => import('../build/register-styles.9udSoNsd.mjs').then(interopDefault),
  "pages/dashboard/security.vue": () => import('../build/security-styles.B6WfoJGn.mjs').then(interopDefault),
  "pages/contact.vue": () => import('../build/contact-styles._Dbr2Tvw.mjs').then(interopDefault),
  "pages/refund-policy.vue": () => import('../build/refund-policy-styles.-38nC3Nk.mjs').then(interopDefault),
  "pages/register/index.vue": () => import('../build/index-styles.CwW23TPb.mjs').then(interopDefault),
  "pages/exhibition.vue": () => import('../build/exhibition-styles.BgqOPFDa.mjs').then(interopDefault),
  "pages/register/exhibitor.vue": () => import('../build/exhibitor-styles.DSTPHNj2.mjs').then(interopDefault),
  "pages/dashboard/payment.vue": () => import('../build/payment-styles.jIO1PiOx.mjs').then(interopDefault),
  "pages/admin/manual-payments.vue": () => import('../build/manual-payments-styles.CDsPguk-.mjs').then(interopDefault),
  "pages/admin/speakers/index.vue": () => import('../build/index-styles-2.CdGZWhWU.mjs').then(interopDefault),
  "pages/admin/reports.vue": () => import('../build/reports-styles.DOSmmwGL.mjs').then(interopDefault),
  "pages/admin/program.vue": () => import('../build/program-styles.DnNq7wPS.mjs').then(interopDefault),
  "pages/admin/announcements.vue": () => import('../build/announcements-styles.DpuSrNFp.mjs').then(interopDefault),
  "pages/dashboard/index.vue": () => import('../build/index-styles-3.BH-w3co_.mjs').then(interopDefault),
  "pages/deal-room.vue": () => import('../build/deal-room-styles.BZo9-zpj.mjs').then(interopDefault),
  "pages/partners.vue": () => import('../build/partners-styles.BeCkCZdr.mjs').then(interopDefault),
  "pages/about.vue": () => import('../build/about-styles.tUxco_7P.mjs').then(interopDefault),
  "pages/index.vue": () => import('../build/index-styles-4.C3SBUrpK.mjs').then(interopDefault),
  "pages/admin/certificates.vue": () => import('../build/certificates-styles.CWchxpvo.mjs').then(interopDefault),
  "pages/admin/users.vue": () => import('../build/users-styles.Ko5d9F-k.mjs').then(interopDefault),
  "pages/admin/packages.vue": () => import('../build/packages-styles.BPn5Ergb.mjs').then(interopDefault),
  "pages/business-matching.vue": () => import('../build/business-matching-styles.BiyXVkey.mjs').then(interopDefault),
  "pages/program/index.vue": () => import('../build/index-styles-5.BYk5r9tG.mjs').then(interopDefault),
  "pages/speakers/index.vue": () => import('../build/index-styles-6.Bjdn641Y.mjs').then(interopDefault),
  "pages/tickets.vue": () => import('../build/tickets-styles.BaUbznHD.mjs').then(interopDefault),
  "pages/register/delegate.vue": () => import('../build/delegate-styles.Bf9FUpHz.mjs').then(interopDefault),
  "pages/dashboard/ticket/index.vue": () => import('../build/index-styles-7.Bj1Sjtli.mjs').then(interopDefault),
  "pages/admin/email-notifications.vue": () => import('../build/email-notifications-styles.Sj071IAL.mjs').then(interopDefault),
  "components/LegalPage.vue": () => import('../build/refund-policy-styles.-38nC3Nk.mjs').then(interopDefault),
  "../node_modules/nuxt/dist/app/components/error-500.vue": () => import('../build/error-500-styles.CgvVbW11.mjs').then(interopDefault),
  "../node_modules/nuxt/dist/app/components/error-404.vue": () => import('../build/error-404-styles.CiqRMCWG.mjs').then(interopDefault)
};

export { styles as default };
//# sourceMappingURL=styles.mjs.map
